<?php
include 'header.phtml';
?>
<div class="message">
    <form name="promotion" method="post" action="/promotion/check">
        <div class="center text">
            ¿Desea canjear el código promocional?
        </div>
        <input type="hidden" name="id" value="<?php echo $params['id']; ?>">
        <div class="center">
            <button type="submit">Canjear código</button>
        </div>
        <div class="center">
            <a href="/">Volver</a>
        </div>
    </form>
</div>
<?php
include 'footer.phtml';
?>