<?php
include 'header.phtml';
?>
<div class="message">
    <form name="promotion" method="post" action="/promotion/new">
        <div class="center text">
            ¿Desea obtener un nuevo código promocional?
        </div>

        <div class="center">
            <button type="submit">Obtener código</button>
        </div>
        <div class="center">
            <a href="/">Volver</a>
        </div>
    </form>
</div>
<?php
include 'footer.phtml';
?>