<?php
include 'header.phtml';
?>

<div class="login">
	<form name="user-login" method="post" action="/login">
		<fieldset>
			<legend>Login</legend>
			<span>Email:</span> <input type="email" name="email">
            <span>Contraseña:</span> <input type="password" name="passwd">
			<?php
			if (isset($params['csrf'])):
			?>
			<input type="hidden" name="csrf" value="<?php echo $params['csrf']; ?>">
			<?php
			endif;
			?>
		</fieldset>

		<div class="center">
			<button type="submit">Login</button>
		</div>
	</form>
	<div class="center">
		<a href="/registro">Registro</a>
	</div>
</div>

<?php
include 'footer.phtml';
?>